apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
      - name: mlapi
        image: unaid1/mlapi:latest
        ports:
        - containerPort: 8000